//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnNet001.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChamCong
    {
        public int MaNV { get; set; }
        public Nullable<System.DateTime> NgayCham { get; set; }
        public bool Cham { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
