//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnNet001.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPhieuNhap
    {
        public Nullable<int> MaPhieuNhap { get; set; }
        public int MaCTPhieuNhap { get; set; }
        public Nullable<int> MaCTSp { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> GiaNhap { get; set; }
        public Nullable<double> TongTien { get; set; }
    
        public virtual CTSanPham CTSanPham { get; set; }
        public virtual PhieuNhap PhieuNhap { get; set; }
    }
}
