//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnNet001.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongKe1
    {
        public int Id { get; set; }
        public Nullable<double> TongNhap { get; set; }
        public Nullable<double> TongXuat { get; set; }
        public string SanPhamTon { get; set; }
        public string SanPhamBanChay { get; set; }
        public Nullable<int> Thang { get; set; }
        public Nullable<double> DoanhThu { get; set; }
        public Nullable<int> SoLuongNhap { get; set; }
        public Nullable<int> SoLuongXuat { get; set; }
        public Nullable<int> SoLuongDonHang { get; set; }
    }
}
